/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package jp.ac.uryukyu.e225717;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        Othello othello = new Othello();
        othello.printBoard();

        /**
         * test欄
         */
        System.out.println(othello.isValid(0, 0, false));
        System.out.println(othello.isValid(2, 3, true));
        // ここまで
    }
}
